redirect to stderr

diff --git a/.chezmoiscripts/common/run_once_01-install-font.sh.tmpl b/.chezmoiscripts/common/run_once_01-install-font.sh.tmpl
--- a/.chezmoiscripts/common/run_once_01-install-font.sh.tmpl
+++ b/.chezmoiscripts/common/run_once_01-install-font.sh.tmpl
@@ -7,6 +7,6 @@
 {{ else if eq .chezmoi.os "darwin" -}}
 {{   include "install/macos/common/font.sh" }}
 {{ else -}}
-    echo "Invalid OS: {{ .chezmoi.os }}"
+    echo "Invalid OS: {{ .chezmoi.os }}" >&2
     exit 1
 {{ end -}}
