update

diff --git a/home/.chezmoiscripts/common/run_once_before_decrypt-private-key.sh.tmpl b/home/.chezmoiscripts/common/run_once_before_decrypt-private-key.sh.tmpl
--- a/home/.chezmoiscripts/common/run_once_before_decrypt-private-key.sh.tmpl
+++ b/home/.chezmoiscripts/common/run_once_before_decrypt-private-key.sh.tmpl
@@ -21,6 +21,9 @@ function decrypt_age_private_key() {
             age --decrypt --output "${age_dst_key}" "${age_src_key}"
             chmod 600 "${age_dst_key}"
         fi
+    else
+        echo "age (https://github.com/FiloSottile/age) is required to decrypt the files." >&2
+        exit 1
     fi
 }
 
